.\"                                      Hey, EMACS: -*- nroff -*-
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH DH-MAKE-GOLANG 1 "2015-07-26"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
dh-make-golang \- automatically creates Debian packaging for Go packages
.SH SYNOPSIS
.B dh-make-golang
.RI [ flags ]
.IR "package"
.SH DESCRIPTION
dh-make-golang is a tool to automatically create Debian packaging for Go
packages. Its goal is to automate away as much of the work as possible when
creating a Debian package for a Go library package.

.SH OPTIONS

Run dh-make-golang \-help for more details.

.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
